language: node_js
node_js:
  - node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: BxnEbx6PxwedbIIYWy6r1pN2as6nIudfrQUwgmucW5MZmI7oQJlIQUx9MbLQFFIhlsWj0X5xM4bH8O2/9+1ZJ+xDqT00qq2VfMfr1MAUqmpJ4PCLpJqp0RY8HuO3dNkiCB9WR3fLeIvYwLLQ7nmr3yCx7rtP5z3raq5377lFEL/dVH8OVfLZYf4YoSvJrqsMPBtA41oTeOV7N3MD0z5zFyB94/5NpvjwqJT7l/ikvKh+Gf9dWU/AIqurRYFkVb463L2UM1MGuFvUHwRI6iJM7cKbOAj0leY6JzO2xrcm2j1MdxdbDjz6T54UuUQn6XMFpqViOUHTbYHDQEPqjNWX4pNk5uUhAa/UKq64Rle2GCvmbmB/liHKXG2dWFJ5w6SXjYP9lvhF3mThTlA7K6iHDLmyUhgv5QiDsIN5FHdcKwuMEzngV01zTVe5NslDvBarc7Lrl7r4Pv/Hm0drAvsgIQY8hy4EYdp1W0v+kfgwfh0AuNEr5JJZsWgti2YE/rMQ5msvGFBFyrzM/Od8slEc6mXrMGMzRG7goxYQgLUQRdNY/Sz4aRuSOz4E209vQmrnUHYbhgeTpXeV+pjd8JoFZ2uuV871HGGGso3S61Bh3TDSI7lWjpCcZL60UoK4JxKzw81f1NiSztD6IJ24NVKAFP4aSkU13MEwxQRQiXGeesA=
  app: leomunds-superhut
  skip_cleanup: true
